#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/sxhkd/bspwmsxhkdrc &
dunst &
pgrep bspswallow || bspswallow &
xbanish &
xrandr --output eDP1 --mode 1366x768 --rotate normal --pos 0x300 --output HDMI1 --primary --mode 1920x1080 --pos 1366x0 &
setxkbmap -option keypad:pointerkeys &

bspc monitor HDMI1 -d 1 2 3 4 5
bspc monitor eDP1 -d 6 7 8 9 10

bspc config border_width	1
bspc config window_gap		0
bspc config pointer_follows_monitor true 
bspc config focus_follows_pointer	true

bspc config focused_border_color	"#ffffff"
bspc config normal_border_color		"#808080"

